[project]
name = "b2b-services"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.116.1",
    "shared",
]

[tool.uv.sources]
shared = { workspace = true }

